#!/usr/bin/env python3
"""
gen_vbt_base.py - regenerate lib/vbt_base.c (the VBT built into the loader).

The loader no longer needs a hand-made t2gmux_vbt.bin: it carries this generic
base VBT (coreboot Whiskey Lake template, only the eDP child on DDI A / AUX-A,
no Intel backlight PWM, fast link training off) and fills in the panel-specific
parts at boot:
  * link rate / lane count / PSR  <- DPCD read through the iGPU's own AUX-A channel
  * native timing                 <- EDID (dGPU GOP handle, else I2C-over-AUX from the panel)

The timing and link values baked in here are placeholders (1920x1080, 4 x HBR2).
PSR is OFF in the base: with PSR on the Intel driver makes the T2 panel flicker.

Usage: python tools/gen_vbt_base.py            (rewrites lib/vbt_base.c)
"""
import os, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def placeholder_edid():
    e = bytearray(128)
    e[0:8] = bytes([0, 255, 255, 255, 255, 255, 255, 0])
    e[8], e[9] = 0x06, 0x10                       # "APP"
    e[18], e[19] = 1, 4
    # 1920x1080 @60 DTD (148.5 MHz) - replaced at boot
    dtd = bytes([0x02, 0x3A, 0x80, 0x18, 0x71, 0x38, 0x2D, 0x40, 0x58, 0x2C,
                 0x45, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1E])
    e[54:72] = dtd
    e[127] = (-sum(e[:127])) & 0xFF
    return bytes(e)


def main():
    with tempfile.TemporaryDirectory() as d:
        edid = os.path.join(d, "edid.bin")
        out = os.path.join(d, "base.vbt")
        open(edid, "wb").write(placeholder_edid())
        subprocess.check_call([sys.executable, os.path.join(HERE, "make_vbt.py"),
                               "--edid", edid, "--lanes", "4", "--rate", "hbr2", "--psr", "off",
                               "-o", out], stdout=subprocess.DEVNULL)
        v = open(out, "rb").read()
    lines = ["// Generated by tools/gen_vbt_base.py - do not edit.\r\n",
             "#include <efi.h>\r\n",
             "const UINT8 _INT_VbtBase[] = {\r\n"]
    for i in range(0, len(v), 16):
        lines.append("    " + ", ".join("0x%02X" % b for b in v[i:i + 16]) + ",\r\n")
    lines.append("};\r\n")
    lines.append("const UINTN _INT_VbtBaseSize = %d;\r\n" % len(v))
    with open(os.path.join(ROOT, "lib", "vbt_base.c"), "wb") as f:
        f.write("".join(lines).encode())
    print("lib/vbt_base.c: %d bytes of VBT" % len(v))


if __name__ == "__main__":
    main()
