#!/usr/bin/env python3
"""Build SSDT_IGPU.aml (mode 4) or SSDT_IGPU_VBT.aml (mode 3) from tools/SSDT_IGPU.asl.

  python tools/make_ssdt_igpu.py                       -o SSDT_IGPU.aml       (no VBT inside, mode 4)
  python tools/make_ssdt_igpu.py --vbt t2gmux_vbt.bin  -o SSDT_IGPU_VBT.aml   (VBT inside, mode 3)

The .asl is only read, never written. The two markers /*VBT_EXTERNALS*/ and /*VBT_BLOCK*/ must be
in it. Needs `iasl` (apt-get install acpica-tools).
"""
import argparse, os, shutil, subprocess, sys, tempfile

MARK_EXT = "/*VBT_EXTERNALS*/"
MARK_BLK = "/*VBT_BLOCK*/"
MAILBOX4_OFFSET = 0x400      # VBT goes to OpRegion + 0x400
MAILBOX4_MAX = 0x1800        # mailbox 4 size


def die(msg):
    print("error: " + msg, file=sys.stderr)
    sys.exit(1)


def vbt_parts(vbt):
    n = (len(vbt) + 7) & ~7                      # buffer size = VBT padded to 8 bytes
    buf = vbt + bytes(n - len(vbt))
    rows = []
    for i in range(0, n, 8):
        rows.append("            " + ", ".join("0x%02X" % b for b in buf[i:i + 8]))
    body = ",\n".join(rows)
    externals = ("External (_SB_.PCI0.IGPU, DeviceObj)\n"
                 "    External (_SB_.PCI0.IGPU.ASLS, FieldUnitObj)\n"
                 "    External (ASLB, FieldUnitObj)")
    block = f"""// VBT delivered through ACPI (mode 3): IGPU._INI copies it to OpRegion+0x{MAILBOX4_OFFSET:X}
    // (mailbox 4) before the Intel driver starts. Generated by make_ssdt_igpu.py, do not edit.
    Scope (\\_SB.PCI0.IGPU)
    {{
        Name (T2VB, Buffer (0x{n:X})
        {{
{body}
        }})

        Method (_INI, 0, Serialized)
        {{
            Local0 = ASLS
            If (((Local0 == Zero) || (Local0 == 0xFFFFFFFF)))
            {{
                Local0 = ASLB
            }}

            If (((Local0 == Zero) || (Local0 == 0xFFFFFFFF)))
            {{
                Return (Zero)
            }}

            OperationRegion (T2OH, SystemMemory, Local0, 0x14)
            Field (T2OH, ByteAcc, NoLock, Preserve)
            {{
                T2S0,   64,
                T2S1,   64,
                T2SZ,   32
            }}

            // signature "IntelGraphicsMem" and OpRegion large enough for mailbox 4
            If (((T2S0 != 0x6172476C65746E49) || (T2S1 != 0x6D654D7363696870)))
            {{
                Return (Zero)
            }}

            If (((T2SZ << 0x0A) < 0x{MAILBOX4_OFFSET + n:X}))
            {{
                Return (Zero)
            }}

            OperationRegion (T2VR, SystemMemory, (Local0 + 0x{MAILBOX4_OFFSET:04X}), 0x{n:X})
            Field (T2VR, ByteAcc, NoLock, Preserve)
            {{
                T2VD,   {n * 8}
            }}

            T2VD = T2VB
            Return (Zero)
        }}
    }}"""
    return n, externals, block


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--asl", default=os.path.join(here, "SSDT_IGPU.asl"), help="source (default: tools/SSDT_IGPU.asl)")
    ap.add_argument("--vbt", help="embed this VBT (mode 3). Without it no VBT is embedded (mode 4).")
    ap.add_argument("-o", "--output", required=True, help="output .aml (do not point it into tools/)")
    ap.add_argument("--keep-asl", action="store_true", help="also write <output>.generated.asl")
    ap.add_argument("--iasl", default="iasl", help="iasl binary")
    a = ap.parse_args()

    if not shutil.which(a.iasl):
        die("iasl not found (apt-get install -y acpica-tools)")
    src = open(a.asl, encoding="utf-8").read()
    for m in (MARK_EXT, MARK_BLK):
        if m not in src:
            die("marker %s is missing in %s" % (m, a.asl))

    if a.vbt:
        vbt = open(a.vbt, "rb").read()
        if len(vbt) == 0:
            die("VBT file is empty")
        if vbt[:4] != b"$VBT":
            die("%s does not start with $VBT" % a.vbt)
        if len(vbt) > MAILBOX4_MAX:
            die("VBT is %d bytes, mailbox 4 holds %d" % (len(vbt), MAILBOX4_MAX))
        n, ext, blk = vbt_parts(vbt)
        print("VBT: %d bytes, T2VB buffer 0x%X (%d) bytes" % (len(vbt), n, n))
    else:
        ext, blk = "", ""
        print("no VBT embedded (mode 4 build)")
    out_asl = src.replace(MARK_EXT, ext).replace(MARK_BLK, blk)

    out = os.path.abspath(a.output)
    if os.path.dirname(out) == os.path.abspath(here):
        die("output must not be inside tools/")
    if a.keep_asl:
        with open(out + ".generated.asl", "w", encoding="utf-8", newline="\n") as f:
            f.write(out_asl)
    with tempfile.TemporaryDirectory() as tmp:
        tasl = os.path.join(tmp, "SSDT_IGPU.asl")
        with open(tasl, "w", encoding="utf-8", newline="\n") as f:
            f.write(out_asl)
        r = subprocess.run([a.iasl, "-p", os.path.join(tmp, "SSDT_IGPU"), tasl], capture_output=True, text=True)
        sys.stdout.write(r.stdout)
        sys.stderr.write(r.stderr)
        aml = os.path.join(tmp, "SSDT_IGPU.aml")
        if r.returncode != 0 or not os.path.exists(aml):
            die("iasl failed")
        shutil.copyfile(aml, out)
    print("wrote %s (%d bytes)" % (out, os.path.getsize(out)))


if __name__ == "__main__":
    main()
